### ISSUE TITLE
Bug in JoinTable

### ISSUE THREAD

**Issue by shawnjhenry** [torch/nn#321]
Hi,

For some reason JoinTable is not always forgetting the size of its previous input when presented with tables of varying size.  Specifically, updateGradInput gets stuck outputting tables of a fixed size after some number of iterations (even 2!).  Here's a minimal example demonstrating this: 

You may have to call it a few times to see the bug.
```
model = nn.Sequential()
model:add(nn.JoinTable(1))

for i=1, 2 do
	local input = {}
	local randomNumber = torch.randperm(30)[1]
	for i=1, randomNumber do
		table.insert(input, torch.randn(100))
	end

	local output = model:forward(input)
	local gradOutput = torch.randn(output:size())
	local grad = model:backward(input, gradOutput)
	print(#input)
	print(#grad)
end
```

**Comment by hughperkins** [comment]
I'm not core, just a casual onlooker but ... AFAIK this is not a bug, this is by design, in order to reduce the number of allocations.  I guess what you could do is have a module that creates your network, and call it each time you want to have inputs/outputs of different sizes.  You can see eg that LSTM has a specific [LSTM.lua](https://github.com/karpathy/char-rnn/blob/master/model/LSTM.lua) module to create the network

**Comment by shawnjhenry** [comment]
Thanks for the info.  I think in my case the solution might be simpler - the other parts of the network already handle inputs of different sizes correctly, so I only need to call a new instance of JoinTable for each training example of new size, right?

**Comment by soumith** [comment]
you are right, this is a bug. preparing a patch for it.

**Comment by hughperkins** [comment]
Hmmm, right.
