### ISSUE TITLE
Variable Table Length Bug

### ISSUE THREAD

**Issue by shawnjhenry** [torch/nn#349]
Hi,

As pointed out in #332, ConcatTable still has the bug that JoinTable and CAddTable did.  I just discovered the same bug in MixtureTable as well.  The script from my last comment in #332 reproduces the bug for ConcatTable and a similar script should reproduce it for MixtureTable as well.  

Thanks,
Shawn

**Comment by soumith** [comment]
cc: @nicholas-leonard can you please send a fix for this.

**Comment by nicholas-leonard** [comment]
Will look into it.

**Comment by nicholas-leonard** [comment]
@soumith so did you fix this with #378 ?

**Comment by soumith** [comment]
I fixed it for ConcatTable, but apparently there's a bug in MixtureTable as well? didn't fix that one.

**Comment by FabbyD** [comment]
Hi there, 

This seems to be an old issue but a guy that used to work where I do seems to have written a fix. I stumbled upon his code while digging for bugs. He commented out all size checks such as:
```lua
if self.batchSize ~= batchSize     >     -- if self.batchSize ~= batchSize
```
and
```lua
if not self.backwardSetup then     >     -- if not self.backwardSetup then
```

He also added this after line 94 of `MixtureTable.lua` to filter invalid gradInputs I believe:
```lua
if #expertGradInputs > #expertInputs then 
   for i=#expertInputs+1, #expertGradInputs do
      expertGradInputs[i] = nil
   end
end
```

I am a little bit hesitant to do a pull request since this is not my code but I wanted to share it with you.

**Comment by nicholas-leonard** [comment]
@FabbyD please do a PR. Torch don't bite :)

**Comment by FabbyD** [comment]
Aye, 2 months later. Here it is. #1149
