### ISSUE TITLE
SpatialConvolutionMM.weight should be 4d, currently 2d

### ISSUE THREAD

**Issue by hughperkins** [torch/nn#406]
SpatialConvolutionMM should be 4d, currently 2d:
https://github.com/torch/nn/blob/master/SpatialConvolutionMM.lua#L19

```
   self.weight = torch.Tensor(nOutputPlane, nInputPlane*kH*kW)
   self.bias = torch.Tensor(nOutputPlane)
   self.gradWeight = torch.Tensor(nOutputPlane, nInputPlane*kH*kW)
   self.gradBias = torch.Tensor(nOutputPlane)
```

I think it should use a view where required internally, but expose the weight as a 4d tensor externally.  (This relates somewhat to https://github.com/torch/nn/pull/398 , which is a similar concept)

**Comment by fmassa** [comment]
If you want the weights to be 4D, why don't you simply use `SpatialConvolution`, which is since https://github.com/torch/nn/commit/bb808d94a1970e1a263f81283d6bc5440eef328d a wrapper around `SpatialConvolutionMM`, but that unviews the weight after each `updateOutput` https://github.com/torch/nn/blob/master/SpatialConvolution.lua#L96 ?

**Comment by hughperkins** [comment]
Great! Thanks! :-)
