### ISSUE TITLE
SpatialPooling and Unpooling with saved pooling indices

### ISSUE THREAD

**Issue by viorik** [torch/nn#425]
I would need an unpooling (upsampling) layer in my architecture that uses the pooling indices from the corresponding pooling layer. I found an implementation for UnPooling in [dc-ign] (https://github.com/willwhitney/dc-ign/blob/master/modules/UnPooling.lua). Is there one that uses saved pooling indices? If there isn't, I could implement it (guess all I need to do is to access the self.indices from the corresponding pooling layer and use it in the unpooling layer?)

**Comment by ysabellee** [comment]
Hi @viorik , have you implemented the unpooling layer?

**Comment by viorik** [comment]
Hi @ysabellee, I implemented a basic version in lua, have a look [here] (https://github.com/viorik/UnPoolIdx). Note that when you set up the model, you need to extract the indices from the corresponding maxpooling layer and pass them as parameter to the unpooling layer. You can see that in the demo script. 
However, in the end I decided not to use this kind of layer for my architecture, so I did not spend time on making it faster, or testing it thoroughly.

**Comment by andreaskoepf** [comment]
I am currently experimenting with a pure-lua SpatialUnpooling module based on the tensor functions scatter/gather. Code is [here](https://gist.github.com/andreaskoepf/2539cf7493dfe032ced3).

**Comment by viorik** [comment]
@andreaskoepf yes, that's probably better than my for loops; a colleague mentioned this possibility few days ago too. I imagine it can support cuda tensors, so it should be more efficient.

**Comment by andreaskoepf** [comment]
@viorik Unfortunately the CPU version of scatter/gather is currently not fully parallelized and since the nn.SpatialMaxPooling module stores indices as double a conversion to long has to be done first.

I saw @clement-masson is working on a [C implementation](https://gist.github.com/clement-masson/38029923fc29ae76c0fd) using omp of SpatialMaxUnpooling.

**Comment by clement-masson** [comment]
Hi.
I have indeed coded a C version (and a Cuda version :) ) with their lua wrapper of SpatialMaxUnpooling that uses the indices computed by a SpatialMaxPooling (in fact I widely used the C and Cuda code of SpatialMaxPool, as the operations involved in pooling and unpooling are very similar. I just had to put everything altogether). 
This unpooling module creates feature maps that put the max values selected by the pooling module back into maps of the same dimensions as the original ones. This way, the sequence max-pooling -> unpooling is equivalent to dividing each feature maps in 2*2 blocks (or larger depending on the pooling parameters) and setting every non-maxima element to zero in every blocks.

It may look a little bit strange because the constructor basically just takes as input a nn.SpatialMaxPooling module. First, this allows to easily have access to this pooling module indices. In addition, I found it was easier to unpool when having access to the original dimensions of the feature maps (before pooling). Therefore, the unpooling module slightly modifies the pooling updateOutput method to also store the dimensions before pooling, so as to easily access them when unpooling.

If you are interested in my solution, I put the code here : https://gist.github.com/clement-masson/c364f53d15e53a2e9812
There is also a Cuda version that I did not put on the gist.
I did not want to create a repo just for sharing those files so I compressed them and uploaded there : 
[cunnMasson.zip](https://github.com/torch/nn/files/51423/cunnMasson.zip)
[nnMasson.zip](https://github.com/torch/nn/files/51424/nnMasson.zip)

To install them, you need to uncompress the zip. Open a terminal in the unzipped directory and enter ``` mkdir build; cd build; cmake ../; make``` . 
If everything goes well, you then just have to (in the case you did not change the name nnMasson and that your torch install directory is in your home. Otherwise, make the necessary changes) 
```cp build/libnnMasson.so ~/torch/install/lib/lua/5.1``` 
``` cp *.lua ~/torch/install/share/lua/5.1/nnMasson``` 

For cuda, it is the same except you add 'cu' before every 'nnMasson' (including the .so)

**Comment by clement-masson** [comment]
@viorik Here is the PR for the final version of SpatialMaxUnpooling : #520 
Alternatively, you can find it on [my fork of nn, on the branch "devMasson"](https://github.com/clement-masson/nn/tree/devMasson)

**Comment by fmassa** [comment]
@clement-masson could you check thr issue in https://github.com/twitter/torch-autograd/issues/50 ?

**Comment by viorik** [comment]
Thanks a lot, @clement-masson. Closing the issue.
