### ISSUE TITLE
SpatialConvolutionMM crashes on ARM

### ISSUE THREAD

**Issue by mvitez** [torch/nn#495]
This commit has changed some int-s to size_t:
https://github.com/torch/nn/commit/8ff64afd442839017207016ec5da3b7f07094f0d

This prevents fmaxf from working, as size_t is an unsigned type and negative values are interpreted as very big positives.

The solution is to cast the second parameter of fmax in these four lines to int:

https://github.com/torch/nn/blob/master/generic/SpatialConvolutionMM.c#L48
https://github.com/torch/nn/blob/master/generic/SpatialConvolutionMM.c#L49
https://github.com/torch/nn/blob/master/generic/SpatialConvolutionMM.c#L110
https://github.com/torch/nn/blob/master/generic/SpatialConvolutionMM.c#L111 

The problem does not appear on 64 bit architectures only because of a chance (rounding and overflow):

size_t a = -1;
(size_t)(double)a gives 0

**Comment by culurciello** [comment]
Hi guys, this i a big issue, it broke all our ARM 32 and 64 bits platforms. please take note

**Comment by fmassa** [comment]
I don't know, I was wondering if it isn't better to revert to before commit https://github.com/torch/nn/commit/8ff64afd442839017207016ec5da3b7f07094f0d and think a bit more thoroughly about a better way to handle huge tensors ?
I mean, the index of the tensors in `TH` is [`long`](https://github.com/torch/torch7/blob/master/lib/TH/generic/THStorage.h#L27), so currently we can't have tensors bigger than the maximum number represented by a `long` anyway.
All the the complications we are facing is because of replacing the `int` by `size_t`. So why don't we replace the `size_t`s by `long`s, instead of having lots of castings etc ?

**Comment by mvitez** [comment]
Yes, sure, changing size_t to long is probably a better idea.

Francisco Massa wrote:

**Comment by culurciello** [comment]
Thank you Francisco and Marko for this

**Comment by culurciello** [comment]
Fixes:
48,49c48,49
<                  lpad = fmaxf(0,padW-kw);
<                  rpad = fmaxf(0,padW-(kW-kw-1));
---
                lpad = fmaxf(0,(int)(padW-kw));
                rpad = fmaxf(0,(int)(padW-(kW-kw-1)));
110,111c110,111
<              lpad = fmaxf(0,padW-kw);
<              rpad = fmaxf(0,padW-(kW-kw-1));
---
            lpad = fmaxf(0,(int)(padW-kw));
            rpad = fmaxf(0,(int)(padW-(kW-kw-1)));

**Comment by culurciello** [comment]
Did anyone make sure this is fixed?

**Comment by soumith** [comment]
fixed via https://github.com/torch/nn/pull/605
