### ISSUE TITLE
Smooth L1 loss vs Huber loss

### ISSUE THREAD

**Issue by Kaixhin** [torch/nn#579]
I was preparing a PR for the [Huber loss](https://en.wikipedia.org/wiki/Huber_loss), which was going to take my code frome [here](https://github.com/Kaixhin/Atari/blob/master/modules/HuberCriterion.lua). Looking through the docs I realised that what has been named the [`SmoothL1Criterion`](https://github.com/Kaixhin/nn/blob/master/doc/criterion.md#smoothl1criterion) is actually the Huber loss with delta set to 1 (which is understandable, since the paper cited didn't mention this).

Suggestions (particularly from @szagoruyko)?

**Comment by fmassa** [comment]
This is similar to the discussion lead by @koray in https://github.com/koraykv/kex/issues/2
Not sure what people think about it now.

**Comment by Kaixhin** [comment]
I would say that the Huber loss really is parameterised by delta, as it defines the boundary between the squared and absolute costs. I don't think there's a straightforward conversion from SmoothL1...

**Comment by andreaskoepf** [comment]
+1 for Huber loss. SmoothL1Criterion should be refactored to use the huber loss backend code. I think it would have been better if Ross had explicitly referenced Huber loss instead of describing the Smooth L1 in the [Fast RCNN paper](http://arxiv.org/abs/1504.08083).

**Comment by andreaskoepf** [comment]
@szagoruyko What is your opinion on C backend-functions for something like Huber loss? Just from a performance standpoint the C backend is probably not worth it and the lua-only solution works nicely with different tensor types. On the other hand it would be nice to have this as C module in THNN in order to evaluate models without lua dependency. Are there some general torch-guidelines when and why a C backend function instead of 'pure lua solutions' should be used (e.g. something like 'all new functionality should be provided in the form of C functions.' or 'Provide a C impl only if there is a significant speed or memory advantage (e.g. executing a non trivial operation per element).')?

**Comment by UmarSpa** [comment]
It seems that Huber loss and smooth_l1_loss are not exactly the same.
Huber loss:
  ```                                              
    0.5 * x^2                  if |x| <= 1         
    0.5 +  |x|                 if |x| > 1          
  ```                                               
smooth_l1_loss:
  ```  
    0.5 * x^2                  if |x| <= 1         
    |x| - 0.5                  if |x| > 1       
  ```  

In torch I could only fine smooth_l1_loss. Is there Huber loss implementation as well ?

**Comment by andreaskoepf** [comment]
@UmarSpa Your version of "Huber loss" would have a discontinuity at x=1 from 0.5 to 1.5 .. that would not make sense. Please refer to [Huber loss](https://en.wikipedia.org/wiki/Huber_loss).

**Comment by UmarSpa** [comment]
oh yeah, right. Thanks for pointing it out !
