### ISSUE TITLE
bad argument #1 to 'updateOutput' (2D or 3D(batch mode) tensor expected)

### ISSUE THREAD

**Issue by arthur-leguennec** [torch/nn#635]
Hi everybody !

I'm trying torch since last week and I have a problem with the temporal convolution.
I'm working on the UCR datasets (see http://www.cs.ucr.edu/~eamonn/time_series_data/) and when I try a convolution, I have this error:
```
/home/arthur/torch/install/bin/luajit: /home/arthur/torch/install/share/lua/5.1/nn/Sequential.lua:44: bad argument #1 to 'updateOutput' (2D or 3D(batch mode) tensor expected)
stack traceback:
	[C]: in function 'updateOutput'
	/home/arthur/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	testTimeSeries.lua:59: in main chunk
	[C]: in function 'dofile'
	...thur/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

I have this model in lua:
```
net = nn.Sequential()
net:add(nn.TemporalConvolution(5, 1, 3))
net:add(nn.ReLU())
net:add(nn.Linear(trainset:sizeData(), 150))
net:add(nn.ReLU())
net:add(nn.Linear(150, #classes))      -- #classes is the number of class in the data
net:add(nn.LogSoftMax())
net = net:cuda()
```

I train my model with `:train()` (but manually, I have the same error).
I understand how convolution works but I don't know how solve this.
I suppose I have to resize my input but how ?
If you can help me, I will be thankful !!

Thanks,
Arthur

**Comment by kmul00** [comment]
Hi,

Can you please provide with the dimension of the input you are using.

**Comment by arthur-leguennec** [comment]
Yes sure,
I test my neural network with the dataset ECG5000_TRAIN (UCR). 
And after some steps of this dataset, the tensor I obtain and I am using is :
```
{
  data : CudaTensor - size: 500x140
  size : function: 0x4136fb00
  label : CudaTensor - size: 500
  sizeData : function: 0x4136fb78
}
```
with `size()` the function for the size of dataset (here 500) and `sizeData()` the function for the data (here 140).

ps: sorry for my english

**Comment by kmul00** [comment]
Hi,

Have a look at the expected data format for [temporal convolution](https://github.com/torch/nn/blob/master/doc/convolution.md#nn.TemporalConvolution) . It should be of **batchSize x nInputFrame x inputFrameSize**. If I understand correctly (correct me if wrong), in your case, `nInputFrame = 1` and `inputFrameSize = 140` .

So the first `TemporalConvolution`  should be of dimension `(1, 1, 3)`, where `1 = nInputFrame and nOutputFrame`, and `kernelSize = 3`. Output from this layer will have dimension `1 x 138` (since, `140 - batchSize + 1`). So the `Linear` layer should be of dimension `(138, 150)`.

Putting all of these together, see if the following works for you:

```lua
net = nn.Sequential()
net:add(nn.TemporalConvolution(1, 1, 3))
net:add(nn.ReLU())
net:add(nn.Linear(trainset:sizeData() - 3 + 1, 150))
net:add(nn.ReLU())
net:add(nn.Linear(150, #classes))      -- #classes is the number of class in the data
net:add(nn.LogSoftMax())
net = net:cuda()
```

**Comment by soumith** [comment]
As @kmul00 pointed out, do read the docs and see what is the input dimensionality.

In the future could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use github issues for bug tracking. We'll happily reply there. Thanks.
