### ISSUE TITLE
CrossEntropyCriterion's weights seems not work

### ISSUE THREAD

**Issue by ppaanngggg** [torch/nn#702]
I am confused about CrossEntropyCriterion's weights

```
cri = nn.CrossEntropyCriterion(torch.Tensor{0.1,0.9})
cri:forward(torch.Tensor{1,1}, 1)
cri:forward(torch.Tensor{1,1}, 2)
```

both 0.69314718055995

**Comment by fmassa** [comment]
This issue you are facing only happens in non-batch mode.
Actually, the behaviour of `ClassNLLCriterion` changed since https://github.com/torch/nn/pull/353, but the documentation hasn't been updated to reflect that,
You can avoid that by setting the `sizeAverage` field of `ClassNLLCriterion` to `false`.
```lua
cri.nll.sizeAverage = false
```

**Comment by ppaanngggg** [comment]
@fmassa Many thank you, :+1:
