### ISSUE TITLE
numeric grad check for re-norm in LookupTable?

### ISSUE THREAD

**Issue by pengsun** [torch/nn#766]
Could check my comments here for the details:
https://github.com/torch/nn/commit/ee1646f2036d1177b7621b1bf86f8a5c247504e6

I'm not sure of it, correct me if i am wrong.

**Comment by colesbury** [comment]
The re-normalization is not differentiable (it's a re-projection), so I think this is the expected behavior.

**Comment by colesbury** [comment]
cc @xianjiec

**Comment by xianjiec** [comment]
Hey @pengsun , as we discussed offline. The re-normalization is implemented as a "parameter change" (i.e., re-projection as @colesbury mentioned) instead of a kind of additional "math operation". Therefore, the back-propagation code should remain the same, and thus no change to the "accGradParameters".
