### ISSUE TITLE
SpatialDilatedConvolution: storage size changes after calling getParameters

### ISSUE THREAD

**Issue by xonobo** [torch/nn#904]
Here is the code sniplet for reproducing the issue.

require('nn')
m = nn.SpatialDilatedConvolution(1, 32, 5, 5, 1, 1, 2, 2, 1, 1)
m.weight:storage():size() --> 800	
params, grad_params = m:getParameters()
m.weight:storage():size() --> 832

**Comment by clement-masson** [comment]
AFAIK this is not a bug, and you can find similar behavior with other modules than SpatialDilatedConvolution.

Just after instantiation, the weight and bias of a module (for modules than have ones) are tensors which own their own storage. Then, when getParameters is called, it does a complex manipulation on the parameters of all modules in your model so that they all share the same storage (for computation reasons, cf https://github.com/torch/nn/blob/master/Module.lua#L164).

See the example below with a simple SpatialConvolution:

```
th> m = nn.SpatialConvolution(1,32,5,5)
th> torch.pointer(m.weight:storage())
10574352	
th> torch.pointer(m.bias:storage())
10581008	
th> p,gp = m:getParameters()
th> torch.pointer(m.weight:storage())
10589280	
th> torch.pointer(m.bias:storage())
10589280	
th> torch.pointer(p:storage())
10589280	
```

**Comment by soumith** [comment]
yea this is not a bug. The weights and biases are now mapped onto the same storage.
If you want the size of weights, do:
m.weight:nElement()

**Comment by xonobo** [comment]
thanks for the clarification and alternative check method.
