### ISSUE TITLE
bugs in nn.Lookuptable when convert this module to cuda

### ISSUE THREAD

**Issue by eriche2016** [torch/nn#955]
Below is the snippet you can try: 
```
model = nn.LookupTable(10, 5)
model = model:cuda() 
model:forward(torch.CudaTensor{0})
```
The problem is using 0 index as input to the nn.Lookuptable will cause out of range problem, 
However, when using cuda, it will be okay. Is this a bug? hope your replies

**Comment by albanD** [comment]
Hi,
It is not ok since it does not do what you expect.
For speed purposes, the only guarantee that you have with `nn.LookupTable` is that called with valid indices, it will behave properly (as on the CPU side). For other indices it is undefined behavior BUT it won't raise an error (boundary check on the indices would slow down everything too much).

**Comment by eriche2016** [comment]
You mean, on GPU side, it won`t raise because the index is not checked to be valid indice?

**Comment by albanD** [comment]
Yes.

**Comment by eriche2016** [comment]
thanks, i got it.
